### .1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like: a) Addition of 2 in all the element  
b) Multiply 3 with all the elements
c) Divide every element by 2

In [4]:
import numpy as np

In [5]:
x=np.array([1,2,3,4,5])

In [6]:
print(x*2)


[ 2  4  6  8 10]


In [7]:
print(x+2)

[3 4 5 6 7]


In [8]:
print(x/2)

[0.5 1.  1.5 2.  2.5]


In [15]:
print(x[::-1])

[5 4 3 2 1]


### Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [20]:

from collections import Counter

x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

def most_frequent(arr):
  count=Counter(arr)
  most_freq_val=count.most_common(1)[0][0]
  indices=np.where(arr==most_freq_val)[0]
  return most_freq_val,indices

most_freq_val_x,indices_x=most_frequent(x)
print(f"Most frequent value in x:{most_freq_val_x},indices:{indices_x}")

most_freq_val_y,indices_y=most_frequent(y)
print(f"Most frequent value in y:{most_freq_val_y},indices:{indices_y}")

Most frequent value in x:1,indices:[0 5 7 8 9]
Most frequent value in y:1,indices:[0 1 2]


### 3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column  
b) Access 3rd row, 1st column

In [22]:

import numpy as np
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


### Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:

import numpy as np
from collections import Counter
import numpy as np
x=np.array([1,2,3,4,5])
print(x*2)
print(x+2)
print(x/2)
print(x[::-1])
z = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(z)
print(y)
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
def most_frequent(arr):
  count=Counter(arr)
  most_freq_val=count.most_common(1)[0][0]
  indices=np.where(arr==most_freq_val)[0]
  return most_freq_val,indices
most_freq_val_x,indices_x=most_frequent(x)
print(f"Most frequent value in x:{most_freq_val_x},indices:{indices_x}")
most_freq_val_y,indices_y=most_frequent(y)
print(f"Most frequent value in y:{most_freq_val_y},indices:{indices_y}")
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])
Aadar=np.linspace(10,100,25)
print(Aadar.ndim)
print(Aadar.shape)
print(Aadar.size)
print(Aadar.dtype)
print(Aadar.nbytes)
print(Aadar.reshape(5,5))
Aadar.T

### 5. Create a 2-D Array of three rows and four columns, named UCS420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ UCS420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ UCS420_<your_name>>.

In [ ]:

import numpy as np
from collections import Counter

UCS420_Aadar=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
mean=np.mean(UCS420_Aadar)
median=np.median(UCS420_Aadar)
max_=np.max(UCS420_Aadar)
min_=np.min(UCS420_Aadar)
unique_elements=np.unique(UCS420_Aadar)
print("Mean:",mean)
print("Median:",median)
print("Max:",max_)
print("Min:",min_)
print("Unique elements:",unique_elements)
reshaped_UCS420_Aadar=UCS420_Aadar.reshape(4,3)
print("Reshaped array:\n",reshaped_UCS420_Aadar)
resized_UCS420_Aadar=np.resize(UCS420_Aadar,(2,3))
print("Resized array:\n",resized_UCS420_Aadar)